/* Canonical game registry — single source of truth for all game metadata.
 * Loaded as a plain script tag; sets window.GAME_REGISTRY.
 * Any page that lists or routes to games should load this first.
 * worker/src/room.js mirrors the paths — keep them in sync manually. */

window.GAME_REGISTRY = [
  {
    id: 'dodge-square',
    title: '닷지 스퀘어',
    description: '끝까지 살아남는 쪽이 이깁니다',
    type: 'SOLO',
    recommendedPlayers: '1명',
    supportedPlayers: '1명',
    playMode: '개인 기록',
    durationSeconds: 60,
    status: 'PLAYABLE',
    icon: 'DS',
    accentColor: '#e74c3c',
    resultLabel: '생존 시간',
    resultUnit: '초',
    resultScale: 0.1,
    resultDecimals: 1,
    path: '/prototypes/dodge-square/index.html',
  },
  {
    id: 'rhythm-tap',
    title: '리듬 탭',
    description: '타이밍이 정확할수록 점수가 올라갑니다',
    type: 'PARTY_ASYNC',
    recommendedPlayers: '2~4명',
    supportedPlayers: '1~4명',
    playMode: '기록 경쟁',
    durationSeconds: 30,
    status: 'PLAYABLE',
    icon: 'RT',
    accentColor: '#ffb845',
    resultLabel: '최종 점수',
    resultUnit: '점',
    resultScale: 1,
    resultDecimals: 0,
    path: '/prototypes/rhythm-tap/index.html',
  },
  {
    id: 'jump-climber',
    title: '말랑프렌즈 점프',
    description: '세 귀요미 중 하나를 골라 얼굴 커스터마이즈와 2인 점프를 즐겨보세요',
    type: 'DUEL_LIVE',
    recommendedPlayers: '1~2명',
    supportedPlayers: '1~2명',
    playMode: '로컬 동시 플레이',
    durationSeconds: 0,
    status: 'PLAYABLE',
    icon: 'MJ',
    accentColor: '#ff7ea8',
    resultLabel: '최고 높이',
    resultUnit: 'm',
    resultScale: 1,
    resultDecimals: 0,
    path: '/prototypes/jump-climber/index.html',
  },
];
