export const QUIZ_BANK = [
  {
    id: 1,
    question: '우리나라의 수도는 어디인가요?',
    options: ['부산', '서울', '대전', '인천'],
    answer: 1,
    explanation: '우리나라 대한민국의 수도는 서울입니다.',
  },
  {
    id: 2,
    question: '1년은 몇 개월인가요?',
    options: ['10개월', '11개월', '12개월', '13개월'],
    answer: 2,
    explanation: '1년은 1월부터 12월까지 총 12개월입니다.',
  },
  {
    id: 3,
    question: '태양계에서 가장 큰 행성은?',
    options: ['지구', '화성', '목성', '토성'],
    answer: 2,
    explanation: '목성은 태양계에서 가장 큰 행성으로, 지구보다 약 11배나 큽니다.',
  },
  {
    id: 4,
    question: '물이 얼면 무엇이 되나요?',
    options: ['수증기', '얼음', '구름', '안개'],
    answer: 1,
    explanation: '물은 0°C 이하에서 얼어 얼음이 됩니다.',
  },
  {
    id: 5,
    question: '우리나라 국기의 이름은?',
    options: ['무궁화', '태극기', '성조기', '일장기'],
    answer: 1,
    explanation: '우리나라 대한민국의 국기는 태극기입니다.',
  },
  {
    id: 6,
    question: '광합성을 하는 생물은?',
    options: ['물고기', '강아지', '식물', '버섯'],
    answer: 2,
    explanation: '식물은 햇빛, 물, 이산화탄소를 이용해 광합성으로 영양분을 만듭니다.',
  },
  {
    id: 7,
    question: '지구의 자전 주기(하루)는 약 얼마인가요?',
    options: ['12시간', '24시간', '48시간', '72시간'],
    answer: 1,
    explanation: '지구는 약 24시간에 한 바퀴 자전합니다. 이것이 하루의 길이입니다.',
  },
  {
    id: 8,
    question: '한글을 만든 왕은?',
    options: ['태조', '정조', '세종대왕', '영조'],
    answer: 2,
    explanation: '세종대왕이 1443년에 훈민정음(현재의 한글)을 창제하였습니다.',
  },
  {
    id: 9,
    question: '소화를 돕는 신체 기관은?',
    options: ['심장', '폐', '뇌', '위'],
    answer: 3,
    explanation: '위는 음식물을 소화시키는 중요한 소화 기관입니다.',
  },
  {
    id: 10,
    question: '심장이 하는 일은?',
    options: ['숨을 쉬게 한다', '혈액을 온몸에 보낸다', '음식을 소화한다', '생각을 한다'],
    answer: 1,
    explanation: '심장은 펌프처럼 혈액을 온몸으로 보내는 역할을 합니다.',
  },
  {
    id: 11,
    question: '바다에서 가장 큰 동물은?',
    options: ['상어', '문어', '흰수염고래', '돌고래'],
    answer: 2,
    explanation: '흰수염고래(대왕고래)는 지구에서 가장 큰 동물로, 길이 30m 이상 자랍니다.',
  },
  {
    id: 12,
    question: '지구를 둘러싼 기체층을 무엇이라 하나요?',
    options: ['성층권', '대기권', '수권', '암권'],
    answer: 1,
    explanation: '지구를 둘러싼 기체(공기) 층을 대기권이라고 합니다.',
  },
  {
    id: 13,
    question: '식물이 자라는 데 꼭 필요하지 않은 것은?',
    options: ['햇빛', '물', '바람', '공기'],
    answer: 2,
    explanation: '식물이 자라려면 햇빛, 물, 공기가 필요하지만 바람은 필수가 아닙니다.',
  },
  {
    id: 14,
    question: '2 + 2 × 3은 얼마인가요?',
    options: ['12', '8', '10', '6'],
    answer: 1,
    explanation: '곱셈을 먼저 합니다. 2 × 3 = 6, 그 다음 2 + 6 = 8입니다.',
  },
  {
    id: 15,
    question: '지구에서 달까지의 거리는 약 얼마인가요?',
    options: ['약 38만 km', '약 1억 km', '약 3만 km', '약 5천 km'],
    answer: 0,
    explanation: '지구에서 달까지의 평균 거리는 약 38만 4,400km입니다.',
  },
  {
    id: 16,
    question: '다음 중 포유류가 아닌 동물은?',
    options: ['고래', '박쥐', '독수리', '토끼'],
    answer: 2,
    explanation: '독수리는 조류(새)입니다. 고래·박쥐·토끼는 모두 포유류입니다.',
  },
  {
    id: 17,
    question: '우리나라에서 가장 긴 강은?',
    options: ['한강', '금강', '낙동강', '영산강'],
    answer: 2,
    explanation: '낙동강은 길이 약 525km로 우리나라에서 가장 긴 강입니다.',
  },
  {
    id: 18,
    question: '빛의 속도는 약 초당 얼마인가요?',
    options: ['약 3만 km', '약 30만 km', '약 300만 km', '약 3000km'],
    answer: 1,
    explanation: '빛의 속도는 약 초당 30만 km(약 299,792km/s)입니다.',
  },
  {
    id: 19,
    question: '사람의 몸에서 뼈는 몇 개인가요?',
    options: ['약 106개', '약 206개', '약 306개', '약 406개'],
    answer: 1,
    explanation: '어른의 몸에는 약 206개의 뼈가 있습니다.',
  },
  {
    id: 20,
    question: '다음 중 가장 가벼운 기체는?',
    options: ['산소', '이산화탄소', '수소', '질소'],
    answer: 2,
    explanation: '수소(H₂)는 원소 중 가장 가볍고, 물질 중에서도 가장 가벼운 기체입니다.',
  },
];
